[GithubAccount]
github_name = 
github_repository_name = 

# As the variable names suggest, in order for the application called “Updater” to check for updates, you must first enter your GitHub username and the name of the GitHub repository.

[UpdateMode]
update_mode = 
releases_tag = 

# If you're going to update your app via GitHub Repo Releases, you should set the `update_mode` variable to `release`, and don't forget to change the `release_tag` variable as well.

[DownloadFileSettings]
file_name = 
file_url = 
chunk_size = 

# Again, as their names suggest, you’ll need to modify the file name, the file URL, and the `chunk_size` variable to suit your needs.

[UpdateCheckSettings]
update_check_url = 
current_ver_file = 

# If you want to enter the update check URL for the relevant app which contains only the version information please modify the `update_check_url` variable.
# If you want to enter the path to the file containing the version information for the application installed on your computer, please modify the `current_ver_file` variable.

[Folder]
update_folder_name = 

# If you want to specify the folder where downloaded update files will be saved, please change the `update_folder_name` variable.