[Icon]
icon = Icon/updater.ico

# If you want to use a different icon for this app, please modify the `icon` variable to include the file path.

[ThemeSettings]
usertheme = dark
pywinstyles_theme = dark

# If you want to use a different color theme for this app, please change the `usertheme` variable. (There are three options: light, dark, and system.)
# If you want to use a different theme for the Windows title bar and the application’s overall appearance, please change the `pywinstyles_theme` variable. (This applies only to Windows operating systems; there are 12 options available: dark, mica, aero, transparent, acrylic, win7, inverse, popup, native, optimized, light, and normal.)

[FontSettings]
userfont = Arial
userfontsize = 15
usertitlefontsize = 20
userfontbold = True

# If you want to use a different font in this app, please change the `userfont` variable.
# If you want to change the font size in this app, please modify the `userfontsize` variable.
# If you want to change the font size of the title in this app, please modify the `usertitlefontsize` variable.
# If you want the text in this app to appear bolder or not to appear at all, please change the `userfontbold` variable. (There are two options: True and False.)

[CornerRadiusSettings]
usercornerradiusvalue = 9

# If you want to adjust the roundness of the buttons in this app, please change the `usercornerradiusvalue` variable.

[ButtonAppearanceSettings]
userbuttoncolor = default
userbuttonhovercolor = default
userbuttontextcolor = default
userbuttonbordercolor = default
userbuttonborderwidth = default

# If you want to change the button color, hover color, text color, border color, or border width in this app, please modify the relevant variables.

[WindowSettings]
userwindowtitlecolor = default
w_default_res = 700x90
w_res = 580x90
updater_btn_place_x = 350 # You generally do not need to change this variable.

# If you want to change the title text color of this application, please modify the `userwindowtitlecolor` variable.
# If you want to change this application's screen resolution in terms of X and Y, modify the w_default_res or w_res variable.