name: OpenSoftware-World/Updater CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Repo Download
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install requirements.txt
        run: pip install -r requirements.txt

      - name: Install Ruff
        run: pip install ruff==0.6.0

      - name: Lint check
        run: ruff check .

      - name: Import Test
        run: python -c "import updater"